Server:
  RunMode: debug
  HttpPort: 8080
  ReadTimeout: 60
  WriteTimeout: 60
Database:
  Username: root
  Password: root
  Host: 127.0.0.1:3306
  DBName: blog-go
  TablePrefix: blog_
  Charset: utf8
  ParseTime: True